name = "zurg-serverless"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables - edit the values below
[vars]
RD_TOKEN = "your_real_debrid_token_here"
BASE_URL = ""
STRM_TOKEN = ""
USERNAME = ""
PASSWORD = ""
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
HIDE_BROKEN_TORRENTS = "true"

# D1 Database - Wrangler will create this automatically on first deploy
[[d1_databases]]
binding = "DB"
database_name = "zurg-serverless"
database_id = "a0f90534-e4cf-44d6-82b5-c8a468b89b20"
